workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

stages:
  - test
  - report


run_test:
    stage: test
#   Docker image to rise a virtual Linux server to run tests on.
    image: python:3.12
    artifacts:
      when: always
      expire_in: 15 days
      paths:
        - allure-report
    before_script:
        # Install Chrome
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - apt-get update && apt-get install -y google-chrome-stable
        # Install JAVA
        - apt-get update && apt-get install -y openjdk-17-jre openjdk-17-jdk
        # Install Allure Reporter
        - wget https://github.com/allure-framework/allure2/releases/download/2.26.0/allure-2.26.0.tgz 
          && tar -zxvf allure-2.26.0.tgz -C /opt/ 
          && ln -s /opt/allure-2.26.0/bin/allure /usr/bin/allure
        # Install Poetry
        - curl -sSL https://install.python-poetry.org | python3 -
        - export PATH="/root/.local/bin:$PATH"  # Adding Poetry binary directory to PATH
        # Install project dependencies
        - poetry install --no-interaction --no-root
    script:
        # Execute Test Cases
        - poetry run pytest tests/test_changing_currency.py -v --mode=ci --alluredir allure-results
    after_script:
        # Generate Allure Report as web html page project source
#        - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: $CI_CD_TOKEN"
#          "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_BRANCH/download?job=pages"'
#        - unzip artifacts.zip
#        - cp -r public/history allure-results
#        - rm -rf public
        - allure generate -c allure-results -o allure-report
#    Continue even if previous steps fail
    allow_failure: true

pages:
  stage: report
  script:
    - mv allure-report/ public/
  artifacts:
    when: always
    expire_in: never
    paths:
      - public